// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTdAk6DxaiZNaY8xuqf7ZmJ3dIhcTd3zw',
    appId: '1:1048226962858:web:c68d953ca6603d8d5e5fd3',
    messagingSenderId: '1048226962858',
    projectId: 'rentcam-7c31c',
    authDomain: 'rentcam-7c31c.firebaseapp.com',
    storageBucket: 'rentcam-7c31c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABt8MI_P81KA-h0HmggPjSCkpav16Ncrc',
    appId: '1:1048226962858:android:d799d51bb8700c9d5e5fd3',
    messagingSenderId: '1048226962858',
    projectId: 'rentcam-7c31c',
    storageBucket: 'rentcam-7c31c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt9wKnrIL3hs7CKYrNqzw8uNtSmVHpW0I',
    appId: '1:1048226962858:ios:e0732b7083650ebe5e5fd3',
    messagingSenderId: '1048226962858',
    projectId: 'rentcam-7c31c',
    storageBucket: 'rentcam-7c31c.firebasestorage.app',
    iosBundleId: 'com.example.rentCam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTdAk6DxaiZNaY8xuqf7ZmJ3dIhcTd3zw',
    appId: '1:1048226962858:web:a894a196c605ecb65e5fd3',
    messagingSenderId: '1048226962858',
    projectId: 'rentcam-7c31c',
    authDomain: 'rentcam-7c31c.firebaseapp.com',
    storageBucket: 'rentcam-7c31c.firebasestorage.app',
  );
}
